import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'fr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  fr: {
    'nav.home': 'Accueil',
    'nav.techniques': 'Techniques',
    'nav.pricing': 'Tarifs',
    'nav.why_turkey': 'Pourquoi la Turquie',
    'nav.about': 'À propos',
    'nav.faq': 'FAQ',
    'nav.contact': 'Contact',
    'nav.before_after': 'Avant/Après',
    'nav.free_diagnosis': 'Diagnostic Gratuit',
    'nav.free_number': 'Numéro gratuit',
    'nav.free': 'Gratuit',

    'hero.title': 'Votre greffe de cheveux en Turquie dès',
    'hero.per_month': '199€/mois',
    'hero.subtitle': 'Et si votre vie changeait aujourd\'hui ?',
    'hero.description': 'La perte de cheveux n\'est pas une fatalité. Votre confiance peut revenir plus vite que vous ne l\'imaginez.',
    'hero.rating': '+2300 avis',
    'hero.cta': 'Commencer maintenant',
    'hero.francophone': 'Accompagnement complet 100% francophone',
    'hero.francophone_desc': 'De la consultation au suivi post-op, en français',
    'hero.certified_clinic': 'Clinique certifiée internationale',
    'hero.certified_clinic_desc': 'Standards d\'excellence, équipement dernière génération',
    'hero.all_inclusive': 'Séjour tout compris organisé',
    'hero.all_inclusive_desc': 'Hôtel 5*, transferts VIP, traducteur personnel',
    'hero.flexible_payment': 'Paiement flexible en 10 fois',
    'hero.flexible_payment_desc': 'Seulement 199€/mois, tout compris sans frais cachés',
    'hero.payment_plan': 'Paiement en 10 fois • Greffe complète jusqu\'à 5000 greffons',
    'hero.get_quote': 'Obtenir mon devis gratuit',
    'hero.free_diagnosis': 'Obtenez votre diagnostic gratuit en 30 secondes',
    'hero.send_photos': 'Décrivez simplement votre situation, recevez une réponse sous 24h',
    'hero.send_my_photos': 'Demander mon diagnostic',
    'hero.call_free': 'Appel gratuit',
    'hero.secure_payment': 'Paiement sécurisé',
    'hero.no_commitment': 'Sans engagement',
    'hero.satisfaction_guaranteed': 'Satisfaction garantie',
    'hero.certified_patients': 'Clinique certifiée • +15 000 patients accompagnés',

    'why.title': 'Pourquoi Cliniqeo Hair transforme des vies',
    'why.subtitle': 'Plus qu\'une greffe capillaire, c\'est une renaissance personnelle que nous vous offrons',
    'why.francophone_title': 'Accompagnement francophone total',
    'why.francophone_desc': 'De votre premier message jusqu\'à votre dernier rendez-vous de suivi, vous êtes pris en charge par une équipe française dédiée. Zéro stress, zéro incompréhension.',
    'why.clinic_title': 'Clinique d\'excellence internationale',
    'why.clinic_desc': 'Partenariat exclusif avec une clinique de renommée internationale, dirigée par des standards européens. Technologie de pointe, hygiène irréprochable, résultats exceptionnels.',
    'why.price_title': 'Prix accessible, qualité premium',
    'why.price_desc': 'Dès 199€/mois en 10 fois sans frais. La même qualité qu\'en France ou en Allemagne pour jusqu\'à 70% moins cher. Aucun frais caché, transparence totale.',
    'why.video_consultation': 'Consultation vidéo en français',
    'why.whatsapp_support': 'Assistance 24/7 par WhatsApp',
    'why.personal_translator': 'Traducteur personnel sur place',
    'why.book_consultation': 'Réserver ma consultation',
    'why.jci_certified': 'Certification JCI internationale',
    'why.experienced_surgeons': 'Chirurgiens +15 ans d\'expérience',
    'why.latest_equipment': 'Équipement dernière génération',
    'why.discover_clinic': 'Découvrir notre clinique',
    'why.payment_10x': 'Paiement en 10 fois sans frais',
    'why.transparent_quote': 'Devis transparent et détaillé',
    'why.satisfaction_guarantee': 'Garantie satisfaction',
    'why.view_pricing': 'Voir nos tarifs',
    'why.all_included': 'Tout est inclus dans votre forfait',
    'why.all_included_desc': 'Un séjour clé en main pensé pour votre confort et votre tranquillité d\'esprit',

    'packages.fue_dhi': 'Greffe FUE ou DHI jusqu\'à 5000 greffons',
    'packages.fue_dhi_desc': 'Technique choisie selon votre profil',
    'packages.hotel_5star': 'Hôtel 5 étoiles 3 nuits avec petit-déjeuner',
    'packages.hotel_desc': 'Confort et bien-être garantis',
    'packages.vip_transfers': 'Transferts VIP privés (aéroport-hôtel-clinique)',
    'packages.vip_desc': 'Véhicule confortable à disposition',
    'packages.french_translator': 'Traducteur francophone personnel',
    'packages.translator_desc': 'Communication fluide garantie',
    'packages.blood_tests': 'Analyses sanguines et médicaments',
    'packages.medical_kit': 'Kit post-opératoire complet',
    'packages.followup_12m': 'Suivi médical personnalisé 12 mois',
    'packages.followup_desc': 'Accompagnement jusqu\'au résultat final',
    'packages.price_total': '1 990€',
    'packages.or_monthly': 'Ou seulement',
    'packages.per_month': '199€/mois',
    'packages.payment_10x': 'Paiement en 10 fois sans frais',
    'packages.hidden_fees': 'Frais cachés',
    'packages.diagnosis_response': 'Réponse diagnostic',
    'packages.satisfaction': 'Satisfaction client',

    'techniques.title': 'FUE ou DHI : la technique adaptée à votre profil',
    'techniques.subtitle': 'Nos experts vous conseillent la méthode la plus efficace selon votre situation',
    'techniques.fue': 'FUE',
    'techniques.fue_full': 'Follicular Unit Extraction',
    'techniques.fue_desc': 'La technique de référence mondiale, éprouvée et documentée. Extraction précise follicule par follicule pour un rendu ultra-naturel.',
    'techniques.fue_price_from': 'À partir de',
    'techniques.fue_invisible_scar': 'Cicatrisation invisible',
    'techniques.fue_scar_desc': 'Aucune cicatrice visible, récupération rapide',
    'techniques.fue_large_areas': 'Idéale pour grandes surfaces',
    'techniques.fue_areas_desc': 'Traite efficacement les calvities étendues',
    'techniques.fue_natural': 'Résultat très naturel',
    'techniques.fue_natural_desc': 'Densité homogène et harmonieuse',
    'techniques.fue_learn_more': 'En savoir plus sur la FUE',
    'techniques.fue_quote': 'Demander un devis FUE',
    'techniques.dhi': 'DHI',
    'techniques.dhi_full': 'Direct Hair Implantation',
    'techniques.dhi_desc': 'La technique la plus moderne avec stylo implanteur CHOI. Précision maximale et récupération express pour un résultat optimal.',
    'techniques.dhi_choi_pen': 'Stylo implanteur CHOI',
    'techniques.dhi_choi_desc': 'Précision chirurgicale au millimètre',
    'techniques.dhi_fast_recovery': 'Récupération ultra-rapide',
    'techniques.dhi_recovery_desc': 'Retour à la vie normale immédiat',
    'techniques.dhi_max_density': 'Densité maximale garantie',
    'techniques.dhi_density_desc': 'Contrôle parfait angle et profondeur',
    'techniques.dhi_learn_more': 'En savoir plus sur la DHI',
    'techniques.dhi_quote': 'Demander un devis DHI',
    'techniques.technique': 'Technique',
    'techniques.up_to_grafts': 'Jusqu\'à {count} greffons',

    'testimonials.title': 'Ce que disent nos patients',
    'testimonials.subtitle': 'Plus de 15 000 patients nous ont fait confiance pour retrouver leur confiance',
    'testimonials.verified_reviews': 'sur +2 300 avis Google vérifiés',

    'before_after.title': 'Photos Avant Après Greffe de Cheveux Turquie',
    'before_after.subtitle': 'Résultats naturels et durables obtenus par nos patients',
    'before_after.see_more': 'Voir plus de résultats',
    'before_after.months': 'mois',
    'before_after.grafts': 'greffons',
    'before_after.technique': 'Technique',

    'faq.title': 'Questions fréquentes',
    'faq.subtitle': 'Tout ce que vous devez savoir avant de vous lancer',
    'faq.see_all': 'Voir toutes les questions',

    'cta.title': 'Votre transformation commence maintenant',
    'cta.subtitle': 'Décrivez votre situation et recevez une première orientation personnalisée sous 24h',
    'cta.features': 'Gratuit • Sans engagement • Réponse garantie en 24h par nos chirurgiens experts',
    'cta.send_now': 'Envoyer ma demande maintenant',
    'cta.stats_patients': 'Patients satisfaits',
    'cta.stats_satisfaction': 'Taux de satisfaction',
    'cta.stats_response': 'Réponse garantie',
    'cta.stats_price': 'Par mois seulement',

    'footer.company': 'Entreprise',
    'footer.services': 'Services',
    'footer.support': 'Support',
    'footer.legal': 'Légal',
    'footer.about_us': 'À propos',
    'footer.our_clinic': 'Notre clinique',
    'footer.team': 'Notre équipe',
    'footer.fue_technique': 'Technique FUE',
    'footer.dhi_technique': 'Technique DHI',
    'footer.beard_transplant': 'Greffe de barbe',
    'footer.contact_us': 'Contactez-nous',
    'footer.faq': 'FAQ',
    'footer.blog': 'Blog',
    'footer.privacy': 'Politique de confidentialité',
    'footer.terms': 'Conditions d\'utilisation',
    'footer.rights': 'Tous droits réservés',
  },
  en: {
    'nav.home': 'Home',
    'nav.techniques': 'Techniques',
    'nav.pricing': 'Pricing',
    'nav.why_turkey': 'Why Turkey',
    'nav.about': 'About',
    'nav.faq': 'FAQ',
    'nav.contact': 'Contact',
    'nav.before_after': 'Before/After',
    'nav.free_diagnosis': 'Free Diagnosis',
    'nav.free_number': 'Free number',
    'nav.free': 'Free',

    'hero.title': 'Your hair transplant in Turkey from',
    'hero.per_month': '€199/month',
    'hero.subtitle': 'What if your life changed today?',
    'hero.description': 'Hair loss is not a fatality. Your confidence can return faster than you imagine.',
    'hero.rating': '+2300 reviews',
    'hero.cta': 'Start now',
    'hero.francophone': 'Complete English-speaking support',
    'hero.francophone_desc': 'From consultation to post-op follow-up, in English',
    'hero.certified_clinic': 'Internationally certified clinic',
    'hero.certified_clinic_desc': 'Excellence standards, latest generation equipment',
    'hero.all_inclusive': 'All-inclusive organized stay',
    'hero.all_inclusive_desc': '5* hotel, VIP transfers, personal translator',
    'hero.flexible_payment': 'Flexible payment in 10 installments',
    'hero.flexible_payment_desc': 'Only €199/month, all-inclusive with no hidden fees',
    'hero.payment_plan': '10 installments • Complete transplant up to 5000 grafts',
    'hero.get_quote': 'Get my free quote',
    'hero.free_diagnosis': 'Get your free diagnosis in 30 seconds',
    'hero.send_photos': 'Tell us about your situation and receive a response within 24h',
    'hero.send_my_photos': 'Request my assessment',
    'hero.call_free': 'Free call',
    'hero.secure_payment': 'Secure payment',
    'hero.no_commitment': 'No commitment',
    'hero.satisfaction_guaranteed': 'Satisfaction guaranteed',
    'hero.certified_patients': 'Certified clinic • +15,000 patients treated',

    'why.title': 'Why Cliniqeo Hair transforms lives',
    'why.subtitle': 'More than a hair transplant, we offer you a personal rebirth',
    'why.francophone_title': 'Total English-speaking support',
    'why.francophone_desc': 'From your first message to your last follow-up appointment, you are taken care of by a dedicated English-speaking team. Zero stress, zero misunderstanding.',
    'why.clinic_title': 'International excellence clinic',
    'why.clinic_desc': 'Exclusive partnership with an internationally renowned clinic, managed by European standards. State-of-the-art technology, impeccable hygiene, exceptional results.',
    'why.price_title': 'Affordable price, premium quality',
    'why.price_desc': 'From €199/month in 10 interest-free installments. Same quality as UK or Germany for up to 70% less. No hidden fees, complete transparency.',
    'why.video_consultation': 'Video consultation in English',
    'why.whatsapp_support': '24/7 WhatsApp assistance',
    'why.personal_translator': 'Personal translator on site',
    'why.book_consultation': 'Book my consultation',
    'why.jci_certified': 'JCI international certification',
    'why.experienced_surgeons': 'Surgeons with 15+ years experience',
    'why.latest_equipment': 'Latest generation equipment',
    'why.discover_clinic': 'Discover our clinic',
    'why.payment_10x': '10 interest-free installments',
    'why.transparent_quote': 'Transparent detailed quote',
    'why.satisfaction_guarantee': 'Satisfaction guarantee',
    'why.view_pricing': 'View our pricing',
    'why.all_included': 'Everything included in your package',
    'why.all_included_desc': 'A turnkey stay designed for your comfort and peace of mind',

    'packages.fue_dhi': 'FUE or DHI transplant up to 5000 grafts',
    'packages.fue_dhi_desc': 'Technique chosen according to your profile',
    'packages.hotel_5star': '5-star hotel 3 nights with breakfast',
    'packages.hotel_desc': 'Comfort and well-being guaranteed',
    'packages.vip_transfers': 'Private VIP transfers (airport-hotel-clinic)',
    'packages.vip_desc': 'Comfortable vehicle at your disposal',
    'packages.french_translator': 'Personal English-speaking translator',
    'packages.translator_desc': 'Smooth communication guaranteed',
    'packages.blood_tests': 'Blood tests and medications',
    'packages.medical_kit': 'Complete post-operative kit',
    'packages.followup_12m': 'Personalized 12-month medical follow-up',
    'packages.followup_desc': 'Support until final result',
    'packages.price_total': '€1,990',
    'packages.or_monthly': 'Or only',
    'packages.per_month': '€199/month',
    'packages.payment_10x': '10 interest-free installments',
    'packages.hidden_fees': 'Hidden fees',
    'packages.diagnosis_response': 'Diagnosis response',
    'packages.satisfaction': 'Customer satisfaction',

    'techniques.title': 'FUE or DHI: the technique adapted to your profile',
    'techniques.subtitle': 'Our experts advise you on the most effective method for your situation',
    'techniques.fue': 'FUE',
    'techniques.fue_full': 'Follicular Unit Extraction',
    'techniques.fue_desc': 'The world reference technique, proven and documented. Precise follicle-by-follicle extraction for an ultra-natural result.',
    'techniques.fue_price_from': 'From',
    'techniques.fue_invisible_scar': 'Invisible scarring',
    'techniques.fue_scar_desc': 'No visible scars, fast recovery',
    'techniques.fue_large_areas': 'Ideal for large areas',
    'techniques.fue_areas_desc': 'Effectively treats extensive baldness',
    'techniques.fue_natural': 'Very natural result',
    'techniques.fue_natural_desc': 'Homogeneous and harmonious density',
    'techniques.fue_learn_more': 'Learn more about FUE',
    'techniques.fue_quote': 'Request FUE quote',
    'techniques.dhi': 'DHI',
    'techniques.dhi_full': 'Direct Hair Implantation',
    'techniques.dhi_desc': 'The most modern technique with CHOI implanter pen. Maximum precision and express recovery for optimal results.',
    'techniques.dhi_choi_pen': 'CHOI implanter pen',
    'techniques.dhi_choi_desc': 'Millimeter surgical precision',
    'techniques.dhi_fast_recovery': 'Ultra-fast recovery',
    'techniques.dhi_recovery_desc': 'Immediate return to normal life',
    'techniques.dhi_max_density': 'Maximum density guaranteed',
    'techniques.dhi_density_desc': 'Perfect angle and depth control',
    'techniques.dhi_learn_more': 'Learn more about DHI',
    'techniques.dhi_quote': 'Request DHI quote',
    'techniques.technique': 'Technique',
    'techniques.up_to_grafts': 'Up to {count} grafts',

    'testimonials.title': 'What our patients say',
    'testimonials.subtitle': 'Over 15,000 patients have trusted us to regain their confidence',
    'testimonials.verified_reviews': 'from 2,300+ verified Google reviews',

    'before_after.title': 'Hair Transplant Before After Photos Turkey',
    'before_after.subtitle': 'Natural and lasting results obtained by our patients',
    'before_after.see_more': 'See more results',
    'before_after.months': 'months',
    'before_after.grafts': 'grafts',
    'before_after.technique': 'Technique',

    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'Everything you need to know before getting started',
    'faq.see_all': 'See all questions',

    'cta.title': 'Your transformation starts now',
    'cta.subtitle': 'Tell us about your situation and receive personalised initial guidance within 24h',
    'cta.features': 'Free • No obligation • 24h guaranteed response from our expert surgeons',
    'cta.send_now': 'Send my request now',
    'cta.stats_patients': 'Satisfied patients',
    'cta.stats_satisfaction': 'Satisfaction rate',
    'cta.stats_response': 'Guaranteed response',
    'cta.stats_price': 'Per month only',

    'footer.company': 'Company',
    'footer.services': 'Services',
    'footer.support': 'Support',
    'footer.legal': 'Legal',
    'footer.about_us': 'About us',
    'footer.our_clinic': 'Our clinic',
    'footer.team': 'Our team',
    'footer.fue_technique': 'FUE Technique',
    'footer.dhi_technique': 'DHI Technique',
    'footer.beard_transplant': 'Beard transplant',
    'footer.contact_us': 'Contact us',
    'footer.faq': 'FAQ',
    'footer.blog': 'Blog',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Use',
    'footer.rights': 'All rights reserved',
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('fr');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
